---
title: "p8105_hw6_elk2149"
author: "Evan Kennedy"
date: "2025-11-26"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(broom)
```

***Problem 1***
```{r}
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/refs/heads/master/homicide-data.csv"
df_homicide = readr::read_csv(url) |> 
  clean_names() |>
  mutate(
    # Make city_state variable
    city_state = str_c(city, state, sep = ", "),
    
    # Binary solved variable
    solved = disposition == "Closed by arrest",
    
    # Make sure age is numeric
    victim_age = as.numeric(victim_age)
  ) |>
  # Drop specific cities
  filter(
    !city_state %in% c(
      "Dallas, TX",
      "Phoenix, AZ",
      "Kansas City, MO",
      "Tulsa, AL"
    ),
    # Keep only White / Black victims
    victim_race %in% c("White", "Black")
  )

#Log Regression for Baltimore

baltimore_df = df_homicide |>
  filter(city_state == "Baltimore, MD") |>
  mutate(
    # sex and race factors, Female as reference
    victim_sex  = relevel(factor(victim_sex), ref = "Female"),
    victim_race = factor(victim_race)
  )

#log regression
baltimore_logreg = glm(
  solved ~ victim_age + victim_sex + victim_race,
  data   = baltimore_df,
  family = binomial()
)

#get ORs and 95% CI
baltimore_logregfit |>
  tidy(conf.int = TRUE, conf.level = 0.95, exponentiate = TRUE)

#OR for male vs female
baltimore_male_or = baltimore_logregfit |>
  filter(term == "victim_sexMale") |>
  select(term, estimate, conf.low, conf.high, p.value)

baltimore_male_or
```

The adjusted odds ratio for a homicide being solved comparing male to female victims, holding age and race constant, was OR = 0.426 (95% CI 0.324, 0.558)

***Problem 2***
***Problem 3***